name: Update Codeforces Stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-codeforces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Codeforces Stats
        run: |
          curl -s "https://codeforces.com/api/user.info?handles=samudra038" > codeforces.json

      - name: Parse and Update README
        run: |
          python3 -c "
import json
import re

# Read stats
with open('codeforces.json', 'r') as f:
    data = json.load(f)

if data.get('status') == 'OK':
    user_info = data['result'][0]
    handle = user_info.get('handle', 'N/A')
    rating = user_info.get('rating', 'Unrated')
    max_rating = user_info.get('maxRating', 'Unrated')
    contribution = user_info.get('contribution', 0)

    # Read README.md
    with open('README.md', 'r') as f:
        readme = f.read()

    # Update README.md
    updated_readme = re.sub(
        r'<!-- CF-STATS -->.*?<!-- CF-STATS-END -->',
        f'<!-- CF-STATS -->\\nHandle: [{handle}](https://codeforces.com/profile/{handle})\\nRating: {rating}\\nMax Rating: {max_rating}\\nContribution: {contribution}\\n<!-- CF-STATS-END -->',
        readme,
        flags=re.DOTALL
    )

    # Write back to README.md
    with open('README.md', 'w') as f:
        f.write(updated_readme)
else:
    print('Error fetching Codeforces stats')
"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Codeforces stats in README"
          git push
