name: Update Codeforces Stats

on:
  schedule:
    - cron: "*/1 * * * *" # Runs every minute
  workflow_dispatch: # Allows manual triggering

jobs:
  update-codeforces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Codeforces Stats
        run: |
          curl -s "https://codeforces.com/api/user.info?handles=samudra038" > codeforces.json

      - name: Parse and Update README
        run: |
          python3 -c "
import json

# Read stats
with open('codeforces.json', 'r') as f:
    data = json.load(f)

if data.get('status') == 'OK':
    user_info = data['result'][0]
    handle = user_info.get('handle', 'N/A')
    rating = user_info.get('rating', 'Unrated')
    max_rating = user_info.get('maxRating', 'Unrated')
    contribution = user_info.get('contribution', 0)
    rank = user_info.get('rank', 'Unranked').capitalize()

    # Create formatted poster-like stats
    cf_poster = (
        '| **Codeforces Stats**        |                                    |\n'
        '|-----------------------------|------------------------------------|\n'
        f'| **Handle**                  | [{handle}](https://codeforces.com/profile/{handle}) |\n'
        f'| **Current Rating**          | {rating}                          |\n'
        f'| **Maximum Rating**          | {max_rating}                      |\n'
        f'| **Rank**                    | {rank}                            |\n'
        f'| **Contribution**            | {contribution}                    |\n'
    )

    # Read README.md
    with open('README.md', 'r') as f:
        readme = f.read()

    # Replace the placeholder section
    updated_readme = readme.replace(
        '<!-- CF-STATS -->',
        cf_poster
    )

    # Write back to README.md
    with open('README.md', 'w') as f:
        f.write(updated_readme)
else:
    print('Error fetching Codeforces stats')
"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Codeforces stats in README"
          git push
