name: Update Codeforces Stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-codeforces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Codeforces Stats
        run: |
          curl -s "https://codeforces.com/api/user.info?handles=samudra038" > codeforces.json

      - name: Parse and Update README
        run: |
          python3 -c "
import json

# Read stats
with open('codeforces.json', 'r') as f:
    data = json.load(f)

user_info = data['result'][0]
rating = user_info.get('rating', 'N/A')
rank = user_info.get('rank', 'N/A')

# Update README.md
with open('README.md', 'r') as f:
    readme = f.read()

updated_readme = readme.replace(
    '<!-- CODEFORCES_STATS -->',
    f'Rating: {rating} • Rank: {rank}'
)

with open('README.md', 'w') as f:
    f.write(updated_readme)
"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Codeforces stats in README"
          git push
